AWSTemplateFormatVersion: '2010-09-09'
Description: 'This stack deploys a sample task definition.'

Parameters:
  pAppName:
    Type: String
    Default: 'sample'
    Description: 'The name of the application'

  pNetworkMode:
    Type: String
    Default: host
    AllowedValues:
      - awsvpc
      - bridge
      - host
      - none

  pVolumeScope:
    Type: String
    Default: shared
    AllowedValues:
      - shared
      - task

  pLogDriver:
    Type: String
    Default: awslogs
    AllowedValues:
      - awsfirelens 
      - awslogs 
      - fluentd 
      - gelf 
      - journald 
      - json-file 
      - splunk 
      - syslog

Resources:
  rSampleExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'

  rSampleTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess'

  rSampleTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${pAppName}-task-definition'
      NetworkMode: !Ref pNetworkMode
      RequiresCompatibilities:
        - EC2
      ExecutionRoleArn: !GetAtt rSampleExecutionRole.Arn
      TaskRoleArn: !GetAtt rSampleTaskRole.Arn
      Cpu: '256'
      Memory: '512'
      Volumes:
        - Name: !Sub '${pAppName}-vol'
          DockerVolumeConfiguration:
            Scope: !Ref pVolumeScope
            Autoprovision: true
      ContainerDefinitions:
        - Name: !Sub '${pAppName}-container-definition'
          Image: 'amazon/aws-for-fluent-bit'
          LogConfiguration:
            LogDriver: !Ref pLogDriver
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Sub '/ecs/${pAppName}'
              awslogs-stream-prefix: ecs
              awslogs-datetime-format: '%Y-%m-%d %H:%M:%S%L'
          Cpu: 32
          Memory: 256
          MountPoints:
            - SourceVolume: !Sub '${pAppName}-vol'
              ContainerPath: !Sub '/var/lib/${pAppName}'
              ReadOnly: false
          Environment:
            - Name: TEST_ENV
              Value: TEST_VALUE
            - Name: TEST_ENV_LOG
              Value: INFO
      Tags:
        - Key: SWA:SampleTag
          Value: 'Sample Tag Value'

